### ISSUE TITLE
Async Support

### ISSUE THREAD

**Issue by bthome** [Wei1234c/Elastic_Network_of_Things_with_MQTT_and_MicroPython#2]
@Wei1234c 

Wanted to get your thoughts on how to use the framework to upload a script that contains my custom code to enable sensors that are connected to the ESP8266.  I believe the way the framework is written is to upload the script and the main is executed, however the upload script takes control of the application and the MQTT listener is no longer able to process messages.  The MQTT subscriber is using the blocked version of the library and not the async custom library that is available.  Can you recommend a solution?
1. Swap out MQTT to use Async?
2. Specific way to write the script that will allow co-processing (I"m not a python expert so not sure how).

Thanks,
Brian

**Comment by Wei1234c** [comment]
If the sensor-related processing functions don't require real-time response, I think that you can upload it as a `plugin.py` file. 

The basic mechanism of asynchronous operation is a loop which picks up events and passes them to assigned handlers. 

The worker runs a loop to check and process in-coming and out-going messages, mainly with `Worker.process_messages` function, you can write your own Worker class and  inherit it, for example:
```
import plugin

class MyWorker(worker_upython.Worker):
...
    def process_messages(self):
        plugin.do_the_jobs()
        super().process_messages()
...
```

and replace `worker_upython.Worker` with `MyWorker` in `node.py`.
